export {default as Transfer} from '@figment-solana/components/Transfer';
export {default as Keypair} from '@figment-solana/components/Keypair';
export {default as Balance} from '@figment-solana/components/Balance';
export {default as Connect} from '@figment-solana/components/Connect';
export {default as Greeter} from '@figment-solana/components/Greeter';
export {default as Getter} from '@figment-solana/components/Getter';
export {default as Deploy} from '@figment-solana/components/Deploy';
export {default as Setter} from '@figment-solana/components/Setter';
export {default as Fund} from '@figment-solana/components/Fund';
